-- First, add the new enum values while keeping OTHER
ALTER TYPE "ProductType" ADD VALUE IF NOT EXISTS 'ADULT_CLOTH';
ALTER TYPE "ProductType" ADD VALUE IF NOT EXISTS 'CHILD_CLOTH';
ALTER TYPE "ProductType" ADD VALUE IF NOT EXISTS 'ADULT_SKI_SET';
ALTER TYPE "ProductType" ADD VALUE IF NOT EXISTS 'CHILD_SKI_SET';
ALTER TYPE "ProductType" ADD VALUE IF NOT EXISTS 'CHILD_SNOWBOARD_SET';
ALTER TYPE "ProductType" ADD VALUE IF NOT EXISTS 'ADULT_SNOWBOARD_SET';
ALTER TYPE "ProductType" ADD VALUE IF NOT EXISTS 'ACCESSORY';

-- Update all products with type "OTHER" to "ADULT_CLOTH"
UPDATE "Product" 
SET "type" = 'ADULT_CLOTH'::"ProductType"
WHERE "type" = 'OTHER';

